### ISSUE TITLE
raccolta color of the day 

### ISSUE THREAD

**Issue by AlessiaBogoni** [VincenzoManto/SmashHex#23]
creare una pagina di raccolta dei color of the day giocati.
tipo un calendario con tutte le caselline e i colori sbloccati/nascosti 
 
almeno una mode giocata? Come mostriamo se il colore di oggi è sbloccato o no? popup all'entrata della pagina (insieme al combo of days) in cui si propone di giocare quel colore? o nella home? 

da capire insieme

**Comment by VincenzoManto** [comment]
come PM, chiedo che sia data priorità a questo
